configured_endpoints: 9
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/supermemory--inc%2Fsupermemory-c8f702729ad60ec4454dfebc881aa9ac6506d1b5be94529ace73bebe250ac1c4.yml
openapi_spec_hash: a22b9eb5e3ab2c3ce96d3e663cf59e18
config_hash: 77849fd95b1e7c5a1691ab43ea3b180a
