configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/supermemory--inc%2Fsupermemory-2dc17adc2b9fedfbcbee5a88d469b66980169c89af5e1475d2a2ee5aeebc503c.yml
openapi_spec_hash: fc7e963d497cf01d350d46cb1ff98732
config_hash: 8477e3ee6fd596ab6ac911d052e4de79
