configured_endpoints: 26
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/supermemory--inc%2Fsupermemory-new-eef92a68d48cbd0da30cae650e608f5114a52305f81c4deea56ef42e4a0ec05b.yml
openapi_spec_hash: 5b9e4ea9387648b156fdcfea9651ff58
config_hash: a69d5c502ffbfb11a2c8ec61ca5823e9
