configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/supermemory--inc%2Fsupermemory-ed398f5eafd7dffae0725ec2f42f2a2b0db528292cee661e9f1cdb1063e6eb7b.yml
openapi_spec_hash: c09b2e00932fc1762acabbe9e5c41390
config_hash: 8477e3ee6fd596ab6ac911d052e4de79
