configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/supermemory--inc%2Fsupermemory-c57750052aa770c1f554e81b2fcdaf9e4c4d2524a0cec568edbee560fde44dde.yml
openapi_spec_hash: 3adaefca8d4d5c84ee4106e8ba10cabb
config_hash: 8477e3ee6fd596ab6ac911d052e4de79
